services:
  monitoreo:
    build: .
    container_name: mikrotik_monitoreo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./topology.json:/app/topology.json:ro
    ports:
     - "8000:8000"
    networks:
      - red-monitoreo

  # 1. El Archivista de Series de Tiempo
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Montamos el archivo de configuración que acabamos de diseñar
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # Volumen persistente para que no se borren las métricas históricas al apagar
      - prometheus_data:/prometheus
    # Permite al contenedor de Prometheus ver el puerto 8000 de tu Fedora
    networks:
      - red-monitoreo

  # 2. La Pantalla de Control y Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persistencia de dashboards, usuarios y configuraciones visuales
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - red-monitoreo

# Volúmenes administrados por Docker en tu disco duro
volumes:
  prometheus_data:
  grafana_data:

networks:
  red-monitoreo:
    driver: bridge