# prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  # Job existente de tus métricas de API/Enlaces
  - job_name: 'agrocisa-api'
    static_configs:
      - targets: ['api:8000']

  # AQUÍ AGREGAS EL NUEVO JOB DE LAS IMPRESORAS:
  - job_name: 'impresoras-agrocisa'
    scrape_interval: 60s
    static_configs:
      - targets: ['printer_exporter:9120']  # Nombre del servicio en docker-compose